---
title: "ToDo"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pierwszy projekt TWD
## Dane PISA

Smieszny pdf w ktorym jest co nieco informacji o pytaniach:\
https://www.oecd-ilibrary.org/docserver/9789264273856-19-en.pdf?expires=1570538884&id=id&accname=guest&checksum=D82A0626AA2869CBC7A2F21A10C55776


Zrobione:\
1. A~ Skrypt `procent_panstw` dzielacy dane na panstwa i podajacy procentowy udzial kazdego z wyroznionych elementow w przystepnej formie. Mozliwa pozniejsza modyfikacja do specyficznych celow.\
2. A~ Tabelki typu `powtarzanie_klasy` informujace o tym w jakich panstwach i jak bardzo uczniowie powtarzali klasy. Najwazniejsza: `powtarzanie_klasy_merged`.\
3. A~ Wykres `posiadanie biurka`. Oczywiście do przyszlej poprawy.\
4. P~ Wszelkie zebrane dane są w pliku: \
 - Europa.R - porównanie Wielkiej Brytanii do innych państw, wyniki względem Europy i państw o najlepszym systemie szkolnictwa \
 - GBR_schools.R - wszystkie porównania uczniów w szkołach w Wielkiej Brytanii (nie opisuję jakie gdyż wyniki są już ogarniete i przedstawione w pliku Raport.Rmd) \

Ciekawe o uczniach:\
1. Posiadanie własnego pokoju do nauki/biórka: `CY6_QST_MS_STQ_PBA_Final`: `ST011Q01TA`\
2. Jak duzo maja samochodow, instrumentow muzycznych?: `ST012Q02TA`\
3. Jak duzo ksiazek?: `ST013Q01TA`\
4. Powtarzanie klasy w kontekscie panstwa: `ST127Q01TA`\
5. Poczucie przynaleznosci spolecznej: `ST034Q01TA`\
6. Uwaga na zajeciach: `ST097Q01TA`, `ST098Q01TA`\
7. Ciekawostka: Jak nazywa sie kurs: `ST065Q01NA`\
8. Uwaga nauczycieli do uczniow: `ST100Q01TA`\
9. Dyskucje o nauce na zajeciach: `ST103Q01NA`\
10. Informacje o postepach: `ST104Q01NA`\
11. Opinia o zanieczyszczeniu srodowiska: `ST092Q01TA`\
12. Zaciekawienie ucznia przedmiotem: `ST094Q01NA`\
13. Cel uczenia sie: `ST113Q01TA`\
14. Jest tam gdzieś pytanie, ile czasu spędzasz na nauce poza szkola.\
15. \

Ciekawe o rodzicach: `cy6_ms_cmb_stu_qqq.sas7bdat`\
1. Dziecko oglada science on TV: `PA002Q01TA`\
2. Czyta science fiction: `PA002Q03TA`\
3. Chodzi na koła naukowe: `PA002Q05TA`\
4. Naprawia zepsute rzeczy: `PA002Q08NA`\
5. Rodzice rozmawiaja z dzieckiem o szkole: `PA003Q01TA`\
6. 
7. 
8. 
9. 
10. 

Cele:\
1. Raport z pierwszej części projektu przedstawia wyniki pobieżnej analizy szkół w Wielkiej Brytanii i uczniów: \

- sprawdzono miedzy soba uczniow ze szkol i ich wyniki \
- rodzicow - skad sa i do jakich szkol wysylaja dzieci \
- wyniki uczniow w podziale na regiony, szkoly i szkoly okreslone poprzez uzyskiwany fundusz \

2. Druga część projektu ma być głębszą analizą - SZUKAMY HISTORII w uzyskanych w pkt. 1. wyników. \

Zadania:\

NOTKA - zrobic wykres o wynikach z podzialem tylko na szkoly prywatne i publiczne \

1. Porównać wyniki uczniow z państwami o podobnym rozwoju - dzielimy na prywatne i publiczne a uczniów na płcie.\

2. Zrobić schemat psychologiczny danych uczniów i porównywać te dane między sobą: \

- wybrać ciekawe zagadnienia do schematu psychologicznego \
- wplyw stresu? tylko co moze na stres wplywac? \

INTERNET : Profil psychologiczny tworzą:\
1. osobowość,\
2. postawy wobec siebie i innych ludzi, dóbr, problemów, spraw spornych i kontrowersyjnych,\
3. sposoby myślenia,\
4. motywy działania,\
5. wyznawane wartości,\
6. poczucie przynależności do rodziny, grupy społecznej, zawodowej i kraju,\
7. stosunek do ryzyka oraz innowacji,\
8. znaczenie przywiązywane do rodzajów, poziomu i sposobów zaspokajania potrzeb.\

Co można wziac: \
 - zainteresowanie rodzicow dzieckiem\
 - pochodzenie rodzicow - Czy urodziles sie w GB? `ST019AQ01T`, Czy twoja mama? `ST019BQ01T`, Czy Twoj tata? `ST019AQ01T`\
 - zamoznosc - `ESCS` $0$ to średnia, i im bardziej na $+$, tym bogatsi\
 - latwosc zawierania znajomosci/jak widzi siebie w szkole/itp\
 - miesiac urodzin `ST003D02T`\



## Co mozna robic:  
Mozna wywolywac funkcje `srednia_sponsorowanych_GBR` na elementach wektora `col_ext`, oraz `srednia_prywatnych_porownanie` na elementach wektora `col`.\

 
## Wykresy (MichBur):
 1. Presja ruwiesnicza.\
 2. Szkoly w wielkiej brytanii(podzial na fundusze).\
 3. w szkolach prywatnych jest duzo nie-brytyjskich dzieci:\
  a) Wyniki testów w zależnosci od narodowości rodziców(lubie ten wykres, ale nie wiem, czy sie nada)\
  b) -Jaki procent uczniów w specyficznych szkołach ma jakich rodziców\
     -Szkoły, do jakich rodzice wysyłają swoje dzieci
 4. Uczenie jezyka(ojczystego i innego). W GBR w szkolach prywatnych rezygnuje sie z jezykow obcych  na rzecz jezyka ojczystego. W Polsce odwrotnie(punkt 4 w `presja ruwiesnicza` w tym dokumencie)\
 5. Zadowolenie z nauki(brak korelacji miedzy publiczna i prywatna) #TODO.\
 
 
 
## Presja ruwiesnicza:
1. `srednia_prywatnych_porownanie(col[9]) # jestem ambitny` anglicy sa bardziej ambitni i `srednia_prywatnych_porownanie(col[10]) # chce byc najlepszy` tu tez
2. `srednia_prywatnych_porownanie(col[24]) # Czuje sie samotny` anglicy bardziej niz polacy i `srednia_sponsorowanych_GBR(col_ext[23])` w szkolach niezaleznych sa bardziej samotni niz w publicznych.\
3. !! `srednia_prywatnych_porownanie(col[28]) # W roku szkolnym spedzilem okolo () godzin na nauce` anglicy ucza sie o godzine dluzej niz my oraz `srednia_sponsorowanych_GBR(col_ext[28])` w szkolach niezaleznych sie opierdzielaja.\
4. !! Jezyk ojczysty i obcy:\
  a) `srednia_prywatnych_porownanie(col[30]) # Jak duzo w tygodniu sie uczylem jezyka ojczystego`, `srednia_prywatnych_porownanie(col[31]) # Jak duzo w tygodniu sie uczylem jezyka obcego` Brytole ucza sie o 0.5 godziny dluzej swojego nz my oraz my sie uczymy o 2 godziny dluzej cudzych niz oni, ale tendencja jest odwrotna: u nas w prywatnych bardziej cisna na cudzy, a u nich na ojczysty jezyk\
  b) `srednia_sponsorowanych_GBR(col_ext[30])`, `srednia_sponsorowanych_GBR(col_ext[31])` w szkolach niezaleznych ucza sie jezykow o 1/3 mniej\
5. !! `srednia_prywatnych_porownanie(col[48]) # Chodze na korki, bo koledzy tesz chodza # 1-prawda, 0-falsz` w prywatnych szkolach jest wieksza prasja na chodzenie na korki, ale jak sie okazuje `srednia_sponsorowanych_GBR(col_ext[48])` nie dotyczy to akademickich.\
Caly zestwa o korkach: `col_ext[44:68]`\
6. `ktopomaga`\



 
 
 