---
title: "PD_2"
output:
  html_document:
    df_print: paged
  pdf_document: default
  html_notebook: default
---

Na co jestem wkurwiony:\
1. Jak to do chuja niema komentarzy w kodzie? Przecierz cały jest okomentowany i wgl.\
2. Plik `TESTY.R` niema być czytelny. Był on plikiem ja mój osobisty urzytek i zapomniałem go usunąć przed wysłaniem plików.\
3. Nie dokonywałem za każdym razem sprawdzania poprawności danych wejściowych ze względu na to, iż wiedziałem co robię. Rozumiem ideę, iż dzięki tego typu linijką kodu zdarza się wyłapać błędy jeśli ktoś się pomyli, jednakże na jednych z zajęć projektowych środowych wspomniała Pani, iż linijki z kodem "stopifnot" są tylko dla naszego ułatwienia i umożliwiają szybsze znalezienie ewentualnych błędów w kodzie.\
4. Nie zgadzam się z punktacją $3$ pkt. za raport `testy.pdf`. Wiem, że jest to maksymalna punktacja za tą część zadania, jednakże uważam, że za włożoną pracę powinienem dostać więcej punktów. Czy gdybym część porównywania metody oryginalnej ze zmodyfikowaną dał do raportu `raport.pdf` dostałbym więkrzą punktację? Umieściłem tą część w "małym" raporcie, poniewarz uważałem, że analiza algorytmu odpowiedniejsza będzie w nim właśnie, a nie patrzyłem na punktację, ponieważ spokojny byłem o wynik ze względu na zapewnienia profesora Gągolewskiego, iż "przeanalizowanie tej zależności na pewno będzie nagrodzone". Czuję, jakby moja praca i tród były niezauwarzone.\
5. Rozróżnienie na metodę `oryginaną` i `zmodyfikowaną` to najważniejsza część raportu. Jest to element pracy domowej z którego jestem najbardziej dumny. Starałem się opisać różnice między tymi implementacjami w rozdziale `Implementacja`. Proszę więc o ponowne sprawdzenie raportu `testy.pdf` ze szczególnym naciskiem na najważniejszą moim zdaniem część, czyli podrozdziały `Wplyw wyboru wartosci wlasnych` oraz `Alaniza roznic miedzy algorytmem normalnym, a zmodyfikowanym`. Starałem się opisać różnice między tymi implementacjami w rozdziale `Implementacja`.\
6. Uważam, iż dokonałem sprawdzenia poprawności mojej implementacji w rozdziale `Analiza algorytmu` w podziale `Bazowy spectral_clustering(X, k, M)`.\
7. W rozdziale `Analiza algorytmu` w podrozdziale `Wplyw standaryzacji` dokonalem analizy jaki wplyw na wyniki danych miała ich standaryzacja. Czym więc jest spowodowane, że mam wypunktowane "Sprawdzenie wpływu standaryzacji powinno się znaleźć w raporcie jednak"?\
8. Każdy wykres opisałem, a nie podpisałem tylko i wyłącznie jednego na całej pracy. # tego jej nie wyślę\
9. Wygenerowane zbiory zostały dołączone. Są w folderze "pd2-zbiory-benchmarkowe\\own" ta, jak jest napisane w pliku `towrzenie_wlasnych_zbiorow.R`.\


Szanowna Pani,

ocena jaką otrzym

pod wieloma względami jestem niezadowolony z oceny jaką otrzymałem za pracę domową nr 2. Uważam, iż wykonany przeze mnie trud nie został doceniony, ani poprawnie oceniony. Byłbym wdzięczny za ponowne przejrzenie mojej pracy, tudzież szersze wytłumaczenie, czemu jest oceniona tak, a nie inaczej. Szczególnie proszę o wytłumaczenie mi następujących Pani komentarzy:


1. "Brakuje sprawdzenia poprawności argumentów funkcji"
Nie dokonywałem za każdym razem sprawdzania poprawności danych wejściowych ze względu na to, iż byłem świadom tego, co dzieje się w kodzie. Rozumiem ideę, iż dzięki tego typu wywołaniom zdarza się wyłapać błędy jeśli ktoś się pomyli, jednakże na jednych z zajęć projektowych środowych wspomniała Pani, iż linijki z kodem "stopifnot" są tylko dla naszego ułatwienia i umożliwiają szybsze znalezienie ewentualnych błędów w kodzie.
2. Nie zgadzam się z punktacją 3 pkt. za raport `testy.pdf`. Wiem, że jest to maksymalna punktacja za tą część zadania, jednakże uważam, że za włożoną pracę powinienem dostać więcej punktów. Czy gdybym część porównywania metody oryginalnej ze zmodyfikowaną dał do raportu `raport.pdf` dostałbym większą punktację? Umieściłem tą część w "małym" raporcie, poniewarz uważałem, że analiza algorytmu odpowiedniejsza będzie w nim właśnie, a nie patrzyłem na punktację, ponieważ spokojny byłem o wynik ze względu na zapewnienia Pana profesora Gągolewskiego, iż "przeanalizowanie tej zależności na pewno będzie nagrodzone". Czuję, jakby moja praca i trud były niezauważone.
3. "Nie do końca rozumiem, skąd rozróżnienie na metodę oryginalną oraz zmodyfikowaną?"
Rozróżnienie na metodę `oryginaną` i `zmodyfikowaną` to najważniejsza część raportu. Jest to element pracy domowej z którego jestem najbardziej dumny. Starałem się opisać różnice między tymi implementacjami w rozdziale `Implementacja`. Proszę więc o ponowne sprawdzenie raportu `testy.pdf` ze szczególnym naciskiem na najważniejszą moim zdaniem część, czyli podrozdziały `Wplyw wyboru wartosci wlasnych` oraz `Alaniza roznic miedzy algorytmem normalnym, a zmodyfikowanym`. Starałem się opisać różnice między tymi implementacjami w rozdziale `Implementacja`.
4. "Brakuje sprawdzenia poprawności implementacji"
Uważam, iż dokonałem sprawdzenia poprawności mojej implementacji w rozdziale `Analiza algorytmu` w podziale `Bazowy spectral_clustering(X, k, M)`.
5. "Sprawdzenie wpływu standaryzacji powinno się znaleźć w raporcie jednak"
W rozdziale `Analiza algorytmu` w podrozdziale `Wplyw standaryzacji` dokonalem analizy jaki wplyw na wyniki danych miała ich standaryzacja.
6. "Wygenerowane zbiory nie zostały dołączone"
Wygenerowane zbiory zostały dołączone. Są w folderze "pd2-zbiory-benchmarkowe\own" ta, jak jest napisane w pliku `towrzenie_wlasnych_zbiorow.R`.



Z poważaniem
Przemysław Chojecki, SherLOCKed.




Przed rozpoczęciem działań podejmuję się powtórzenia:\
1. Algorytm k-średnich, czyli któreśtam labki\
2. Diagonalizacja macierzy\
a) Algebra, zeszycik\
b) YouTube, jakieś coś w praktyce\
3. Szukaj info o "Zadaniu analizy skupień", dwie książki z ichnego PDFa i jakiś google obowiązkowo\
a) Spectacular Clastering, nawet na YouTube są jakieś wykłady, wizualizacje\
4. Pobrać repozytotium ze zbiorami benchmarkowymi\
a) Załadować kilka z nich do RStudio i plotnąć je, zobaczyć to to w zasadzie jest.\
b) Załadować "podziały ekspertów"(pewnie Gągolewski to zrobił nie oszukujmy się) i zobaczyć jaki ma być efekt tego, co w zasadzie mamy zrobić.\
5. Przerobić wykładziki z PDU (o analizie napisów i pracy z plikami), po to, aby wiedzieć, gdzie szybko znaleść info jak będzie najbardziej potrzebne.\
6. 2 metody zprawdzania jakości wyników:\
a) indeks Fowlkesa-Mallowsa (FM), *dendextend::FM_index*\
b) skorygowany indeks Randa (AR), *mclust::adjustedRandIndex*\
Do obu podali jakieś książki\
7. Przekształcenie Laplasa\
8. Zastanowić się, jak wygenerować własne dane do urzytku. Na 3 sposoby.
9. Napowtórzyć się GITa.\


Do zrobienia jest:\
1. Implementacja algorytmu spektrualnego\
2. Algorytmy z funkcji *hclust()*\
3. Algorytm **Genie** z pakietu *genie*\
4. Jakiś inny algorytm z dowolnego pakietu z CRAN\


Algorytm:\
1. \
2. \


INFO:\
1. Aby porównać algorytmy ze sobą bierzemy najleprze wyniki z danego algorytmu, bo możemy każdy odpalać na różnych parametrów.\
2. Zbadajmy wpływ standaryzacji zmiennych.\
3. Można korzystać z innych bibliotek, np. przy wyszukiwania w głąb lub w szeż.\
4. Skatterplot3D - biblioteka w R do rysowania w 3D, albo R3DInteractivePlot

```{r}
print("dupa")
```





# Zrodzone pytania:
1. Co to znaczy "co najmniej jeden inny algorytm z jakiegoś pakietu na CRAN"?
2. Jak dostosować funkcję order, aby nie sortowała wszystkich wyników, tylko znalazła mi M najwiękrzych, np. 2 najwiękrze z 100000 wyników?
3. Jak wyciszyć efekt funkcji dplyr::top_n?



# BEKA z maxymalizacji
$A$-macierz, $x$-wektor
$$\frac{\partial}{\partial x} x^TAx = (A+A^T)x$$
 Jeśli $A=A^T$
$$\frac{\partial}{\partial x} x^TAx = 2Ax$$
$$\frac{\partial^2}{\partial x^2} x^TAx = 2A$$
Poza tym:
$$\nabla f(x, y, z) = \left[ \begin{array} {c}\frac{\partial}{\partial x}\ f(x, y, z)\\ \frac{\partial}{\partial y}\ f(x, y, z)\\\frac{\partial}{\partial z}\ f(x, y, z) \end{array} \right]$$
Dla $f(x,y,z)$ i $g(x, y, z)$ i stałej $c$ mamy:
$$\mathcal{L}(x,y,z,\lambda)=f(x,y,z)-\lambda\Bigl(g(x,y,z)-c\Bigr)$$
Tw:\
$0$-wektor zerowy\
Maksima i minima funkcji $f$ spełniające warunek $g(x,y,z)=c$ są rozwiazaniami równania:
$$\nabla\mathcal{L}=0$$

## min $x^TAx$
Szukamy najmniejszej wartości $x^TAx$ dla takich $x$, że $x^Tx=1$ oraz przy założeniu, że $A=A^T$ oraz $A$ to macierz nieujemna, czyli:
$$\forall{x\text{-wektor}}\ x^TAx\ge0$$
Co jest równoznaczne z tym, że wszystkie wartości własne manierzy A są nieujemne.\
Aby policzyć minimum liczymy pochodną:
$$\frac{\partial}{\partial x} (x^TAx - \lambda(x^Tx-1))=\frac{\partial}{\partial x} (x^TAx - \lambda x^Tx-\lambda)) = \frac{\partial}{\partial x} (x^TAx - \lambda x^T\cdot I\cdot x-\lambda)) = 2Ax-\lambda2x$$
Przyrównując ją do zera:
$$\frac{\partial}{\partial x} (x^TAx - \lambda(x^Tx-1))=0 \iff 2Ax=\lambda2x \iff Ax=\lambda x \iff x\text{ jest wektorem własnym}$$
Aby to na pewno było minimum, druga pochodna musi być dodatnia.
$$\frac{\partial^2}{\partial x^2} (x^TAx - \lambda(x^Tx-1)) = \frac{\partial}{\partial x} (2Ax-\lambda2x) = 2A-2\lambda$$
NOTE:\
Aby policzone woktory były minimami/maksimami/punktami przegięcia funkcji $x^TAx$ jej druga pochoda musi się zerować, czyli:
$$\frac{d^2}{dx^2} (x^TAx) = 2A$$
Czyli, jeśli wszystkie wartości własne wyjdą nam ujemne, to odpowiadające im wektory własne będą maksimami, a jeśli wartości własne będą dodatnie, to wektory własne będą minimami.

## który wektor wlasny?
Macierz może posiadać wiele wektorów własnych, tak jak funkcja może mieć wiele minimów. Najmniejszy będzie ten, którego wartość własna $\lambda$ będzie najmniejsza.



# Jaz zrobić clustering dobrze?
Jeśli mamy zbiór punkrów w $\mathbb{R}^{n}$, to każdy z nich jest odległy on innegow wybranej przez nas metryce. Zbieramy te odległości w macierz $W$ taką, że na diagonali są odległości punktu od siebie samego, czyli $0$, i na dodatek jest ona symetryczna, bo metryka i odległość $a$ do $b$ jest taka sama jak w drugą stronę.\
Zdefiniujmy sobie wektor $D_w:=\left[\begin{array}{c}d_1\\d_i\\d_n\end{array}\right]$, który dla $d_i=\sum_j w_{ij}$, czyli suma po wszystkich odległościach od innych punktów.\
Niech jeszcze $D$ będzie macierzą diagonalną taką, że na $ii$-tej pozycji jest $d_i$.
Zdefiniujmy wektor $F:=\left[\begin{array}{c}f_1\\f_i\\f_n\end{array}\right]$, przykład: $F=\left[\begin{array}{c}0\\1\\1\\0\\0\end{array}\right]$ oznacza, że drugi i trzeci punkt są razem w grupie. Jest to podział. Zdefiniujmy wartość tego podziału jako: $R:=\sum_{ij} w_{i,j}(f_i-f_j)^2$, czyli suma odległości wszystkich tych obserwacji, które są w różnych grupach. Jeśli znajdziemy minimum tej funkcji, to będzie to najleprzy podział.

## szukamy minimum $R$
$$R=\sum_{ij} w_{i,j}(f_i-f_j)^2=\sum_{ij} w_{i,j}(f_i^2-2f_if_j+f_j^2)=\sum_{ij}( w_{i,j}f_i^2-2w_{i,j}f_if_j+w_{i,j}f_j^2)=\sum_{ij} w_{i,j}f_i^2-\sum_{ij}2w_{i,j}f_if_j+\sum_{ij}w_{i,j}f_j^2=$$
$$=2\sum_{ij} w_{i,j}f_i^2-2\sum_{ij}w_{i,j}f_if_j$$

## A
$$\sum_{ij} w_{i,j}f_i^2=\sum_i\sum_j (w_{i,j}f_i^2)=\sum_i \Big((\sum_j w_{i,j})f_i^2\Big)=\sum_i \Big(d_if_i^2\Big) = F^TDF$$

## B
$$\sum_{ij}w_{i,j}f_if_j = \sum_i \Big( f_i \sum_j (w_{i,j}f_j) \Big) = \sum_i \Big( f_i \big(\left[\begin{array}{ccc}w_{i,1},\ w_{i,2},\ w_{i,3}, \ \dots\end{array}\right]\cdot\left[\begin{array}{c}f_1\\f_2\\f_3\\\vdots\end{array}\right]\big)\Bigr) = \sum_i \Big( f_i \big(\left[\begin{array}{ccc}w_{i,1},\ w_{i,2},\ w_{i,3}, \ \dots\end{array}\right]\cdot F\big)\Bigr) =$$
$$= \sum_i \Big( \big(f_i \left[\begin{array}{ccc}w_{i,1},\ w_{i,2},\ w_{i,3}, \ \dots\end{array}\right]\big)\cdot F\Bigr) = \big(f_1 \left[\begin{array}{ccc}w_{1,1},\ w_{1,2},\ w_{1,3}, \ \dots\end{array}\right]\big)\cdot F+\big(f_2 \left[\begin{array}{ccc}w_{2,1},\ w_{2,2},\ w_{2,3}, \ \dots\end{array}\right]\big)\cdot F + \dots =$$
$$= \Big(\big(f_1 \left[\begin{array}{ccc}w_{1,1},\ w_{1,2},\ w_{1,3}, \ \dots\end{array}\right]\big)+\big(f_2 \left[\begin{array}{ccc}w_{2,1},\ w_{2,2},\ w_{2,3}, \ \dots\end{array}\right]\big) + \dots \Big)F = \Bigg(\left[\begin{array}{ccc}f_{1},\ f_{2},\ f_{3}, \ \dots\end{array}\right]\cdot\left[\begin{array}{c}[w_{1,1}, w_{1,2}, w_{1,3},\dots]\\ [w_{2,1},w_{2,2},w_{2,3},\dots]\\ [w_{3,1},w_{3,2},w_{3,3},\dots]\end{array}\right]\Bigg) F$$
$$= F^TWF$$

## magicznie:
$$\frac{1}{2} R = F^TDF - F^TWF = F^T(D-W)F$$
Dlatego macierz $D-W$ jest taka ważna i nazywa się Laplacian. $L:=D-W$\
Stąd znalezienie minimum $R$ jest tym samym, co znalezienie minimum $F^TLF$.\
Wyżej pokazałem, że minima $F^TLF$ to wektory własne macierzy $L$ odpowiadające najmniejszym wartością własnym. To one wyznaczają nam podział zbioru.











